### ISSUE TITLE
Need to add proper path for templates

### ISSUE THREAD

**Issue by 4lch3mis7** [prasant-paudel/nuclipy#1]
## Need to add proper path for templates
```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\prash\AppData\Roaming\Python\Python39\site-packages\nuclipy\__main__.py", line 24, in <module>
    main()
  File "C:\Users\prash\AppData\Roaming\Python\Python39\site-packages\nuclipy\__main__.py", line 20, in main
    Scanner(args)
  File "C:\Users\prash\AppData\Roaming\Python\Python39\site-packages\nuclipy\scanner.py", line 26, in __init__
    self.templates = [join(PKG_ROOT, "templates/", _) for _ in listdir("templates/")]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'templates/'
```

**Comment by 4lch3mis7** [comment]
Fixed in version 1.0.3
